// <auto-generated />
namespace Patholabs_Express.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewFile));
        
        string IMigrationMetadata.Id
        {
            get { return "202106220914409_NewFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
